export type PieceType = {
  id: number;
  tile: string;
  suit: string;
  value?: number;
};

export const createPiece = (
  id: number,
  tile: string,
  suit: string,
  value?: number,
): PieceType => ({
  id,
  tile,
  value,
  suit,
});

export const getPicturePath = (piece: PieceType) => {
  const path = `/assets/${piece.tile}/${
    piece.value ? `${piece.suit}_${piece.value}.svg` : `${piece.suit}.svg`
  }`;

  return path;
};

export const initialPieces: PieceType[] = [
  // Bamboo tiles
  createPiece(1, "tiao", "tiao", 1),
  createPiece(2, "tiao", "tiao", 2),
  createPiece(3, "tiao", "tiao", 3),
  createPiece(4, "tiao", "tiao", 4),
  createPiece(5, "tiao", "tiao", 5),
  createPiece(6, "tiao", "tiao", 6),
  createPiece(7, "tiao", "tiao", 7),
  createPiece(8, "tiao", "tiao", 8),
  createPiece(9, "tiao", "tiao", 9),
  createPiece(10, "tiao", "tiao", 1),
  createPiece(11, "tiao", "tiao", 2),
  createPiece(12, "tiao", "tiao", 3),
  createPiece(13, "tiao", "tiao", 4),
  createPiece(14, "tiao", "tiao", 5),
  createPiece(15, "tiao", "tiao", 6),
  createPiece(16, "tiao", "tiao", 7),
  createPiece(17, "tiao", "tiao", 8),
  createPiece(18, "tiao", "tiao", 9),
  createPiece(19, "tiao", "tiao", 1),
  createPiece(20, "tiao", "tiao", 2),
  createPiece(21, "tiao", "tiao", 3),
  createPiece(22, "tiao", "tiao", 4),
  createPiece(23, "tiao", "tiao", 5),
  createPiece(24, "tiao", "tiao", 6),
  createPiece(25, "tiao", "tiao", 7),
  createPiece(26, "tiao", "tiao", 8),
  createPiece(27, "tiao", "tiao", 9),
  createPiece(28, "tiao", "tiao", 1),
  createPiece(29, "tiao", "tiao", 2),
  createPiece(30, "tiao", "tiao", 3),
  createPiece(31, "tiao", "tiao", 4),
  createPiece(32, "tiao", "tiao", 5),
  createPiece(33, "tiao", "tiao", 6),
  createPiece(34, "tiao", "tiao", 7),
  createPiece(35, "tiao", "tiao", 8),
  createPiece(36, "tiao", "tiao", 9),
  // ... repeat for three more sets of Bamboo tiles (total 4 sets)

  // Character tiles
  createPiece(37, "wan", "wan", 1),
  createPiece(38, "wan", "wan", 2),
  createPiece(39, "wan", "wan", 3),
  createPiece(40, "wan", "wan", 4),
  createPiece(41, "wan", "wan", 5),
  createPiece(42, "wan", "wan", 6),
  createPiece(43, "wan", "wan", 7),
  createPiece(44, "wan", "wan", 8),
  createPiece(45, "wan", "wan", 9),
  createPiece(46, "wan", "wan", 1),
  createPiece(47, "wan", "wan", 2),
  createPiece(48, "wan", "wan", 3),
  createPiece(49, "wan", "wan", 4),
  createPiece(50, "wan", "wan", 5),
  createPiece(51, "wan", "wan", 6),
  createPiece(52, "wan", "wan", 7),
  createPiece(53, "wan", "wan", 8),
  createPiece(54, "wan", "wan", 9),
  createPiece(55, "wan", "wan", 1),
  createPiece(56, "wan", "wan", 2),
  createPiece(57, "wan", "wan", 3),
  createPiece(58, "wan", "wan", 4),
  createPiece(59, "wan", "wan", 5),
  createPiece(60, "wan", "wan", 6),
  createPiece(61, "wan", "wan", 7),
  createPiece(62, "wan", "wan", 8),
  createPiece(63, "wan", "wan", 9),
  createPiece(64, "wan", "wan", 1),
  createPiece(65, "wan", "wan", 2),
  createPiece(66, "wan", "wan", 3),
  createPiece(67, "wan", "wan", 4),
  createPiece(68, "wan", "wan", 5),
  createPiece(69, "wan", "wan", 6),
  createPiece(70, "wan", "wan", 7),
  createPiece(71, "wan", "wan", 8),
  createPiece(72, "wan", "wan", 9),
  // ... repeat for three more sets of Character tiles (total 4 sets)

  // Dot tiles
  createPiece(73, "bing", "bing", 1),
  createPiece(74, "bing", "bing", 2),
  createPiece(75, "bing", "bing", 3),
  createPiece(76, "bing", "bing", 4),
  createPiece(77, "bing", "bing", 5),
  createPiece(78, "bing", "bing", 6),
  createPiece(79, "bing", "bing", 7),
  createPiece(80, "bing", "bing", 8),
  createPiece(81, "bing", "bing", 9),
  createPiece(82, "bing", "bing", 1),
  createPiece(83, "bing", "bing", 2),
  createPiece(84, "bing", "bing", 3),
  createPiece(85, "bing", "bing", 4),
  createPiece(86, "bing", "bing", 5),
  createPiece(87, "bing", "bing", 6),
  createPiece(88, "bing", "bing", 7),
  createPiece(89, "bing", "bing", 8),
  createPiece(90, "bing", "bing", 9),
  createPiece(91, "bing", "bing", 1),
  createPiece(92, "bing", "bing", 2),
  createPiece(93, "bing", "bing", 3),
  createPiece(94, "bing", "bing", 4),
  createPiece(95, "bing", "bing", 5),
  createPiece(96, "bing", "bing", 6),
  createPiece(97, "bing", "bing", 7),
  createPiece(98, "bing", "bing", 8),
  createPiece(99, "bing", "bing", 9),
  createPiece(100, "bing", "bing", 1),
  createPiece(101, "bing", "bing", 2),
  createPiece(102, "bing", "bing", 3),
  createPiece(103, "bing", "bing", 4),
  createPiece(104, "bing", "bing", 5),
  createPiece(105, "bing", "bing", 6),
  createPiece(106, "bing", "bing", 7),
  createPiece(107, "bing", "bing", 8),
  createPiece(108, "bing", "bing", 9),
  // ... repeat for three more sets of Dot tiles (total 4 sets)

  // Wind tiles
  createPiece(109, "feng", "dong", null),
  createPiece(110, "feng", "nan", null),
  createPiece(111, "feng", "xi", null),
  createPiece(112, "feng", "bei", null),
  createPiece(113, "feng", "dong", null),
  createPiece(114, "feng", "nan", null),
  createPiece(115, "feng", "xi", null),
  createPiece(116, "feng", "bei", null),
  createPiece(117, "feng", "dong", null),
  createPiece(118, "feng", "nan", null),
  createPiece(119, "feng", "xi", null),
  createPiece(120, "feng", "bei", null),
  createPiece(121, "feng", "dong", null),
  createPiece(122, "feng", "nan", null),
  createPiece(123, "feng", "xi", null),
  createPiece(124, "feng", "bei", null),
  // ... repeat for three more sets of Wind tiles (total 4 sets)

  // Dragon tiles
  createPiece(125, "dragon", "zhong", null),
  createPiece(126, "dragon", "fa", null),
  createPiece(127, "dragon", "bai", null),
  createPiece(128, "dragon", "zhong", null),
  createPiece(129, "dragon", "fa", null),
  createPiece(130, "dragon", "bai", null),
  createPiece(131, "dragon", "zhong", null),
  createPiece(132, "dragon", "fa", null),
  createPiece(133, "dragon", "bai", null),
  createPiece(134, "dragon", "zhong", null),
  createPiece(135, "dragon", "fa", null),
  createPiece(136, "dragon", "bai", null),
];
