export type PieceType = {
    id: number,
    tile: string,
    suit: string,
    value?: number,
}

export const createPiece = (id: number, tile: string, suit: string, value?: number): PieceType => ({
    id,
    tile,
    value,
    suit,
});

export const initialPieces: PieceType[] = [
    // Bamboo tiles
    createPiece(1, 'tiao', 'tiao', 1),
    createPiece(2, 'tiao', 'tiao', 2),
    createPiece(3, 'tiao', 'tiao', 3),
    createPiece(4, 'tiao', 'tiao', 4),
    createPiece(5, 'tiao', 'tiao', 5),
    createPiece(6, 'tiao', 'tiao', 6),
    createPiece(7, 'tiao', 'tiao', 7),
    createPiece(8, 'tiao', 'tiao', 8),
    createPiece(9, 'tiao', 'tiao', 9),
    createPiece(10, 'tiao', 'tiao', 2),
    createPiece(11, 'tiao', 'tiao', 4),
    createPiece(12, 'tiao', 'tiao', 4),
    createPiece(13, 'tiao', 'tiao', 5),
    createPiece(14, 'tiao', 'tiao', 5),
    createPiece(15, 'tiao', 'tiao', 6),
    createPiece(16, 'tiao', 'tiao', 7),
    createPiece(17, 'tiao', 'tiao', 8),
    createPiece(18, 'tiao', 'tiao', 9),
    createPiece(19, 'tiao', 'tiao', 1),
    createPiece(20, 'tiao', 'tiao', 2),
    createPiece(21, 'tiao', 'tiao', 3),
    createPiece(22, 'tiao', 'tiao', 4),
    createPiece(23, 'tiao', 'tiao', 5),
    createPiece(24, 'tiao', 'tiao', 6),
    createPiece(25, 'tiao', 'tiao', 7),
    createPiece(26, 'tiao', 'tiao', 8),
    createPiece(27, 'tiao', 'tiao', 9),
    createPiece(28, 'tiao', 'tiao', 1),
    createPiece(29, 'tiao', 'tiao', 2),
    createPiece(30, 'tiao', 'tiao', 3),
    createPiece(31, 'tiao', 'tiao', 4),
    createPiece(32, 'tiao', 'tiao', 5),
    createPiece(33, 'tiao', 'tiao', 6),
    createPiece(34, 'tiao', 'tiao', 7),
    createPiece(35, 'tiao', 'tiao', 8),
    createPiece(36, 'tiao', 'tiao', 9),
    // ... repeat for three more sets of Bamboo tiles (total 4 sets)

    // Character tiles
    createPiece(37, 'Character', 'Character', 1),
    createPiece(38, 'Character', 'Character', 2),
    createPiece(39, 'Character', 'Character', 3),
    createPiece(40, 'Character', 'Character', 4),
    createPiece(41, 'Character', 'Character', 5),
    createPiece(42, 'Character', 'Character', 6),
    createPiece(43, 'Character', 'Character', 7),
    createPiece(44, 'Character', 'Character', 8),
    createPiece(45, 'Character', 'Character', 9),
    createPiece(46, 'Character', 'Character', 1),
    createPiece(47, 'Character', 'Character', 2),
    createPiece(48, 'Character', 'Character', 3),
    createPiece(49, 'Character', 'Character', 4),
    createPiece(50, 'Character', 'Character', 5),
    createPiece(51, 'Character', 'Character', 6),
    createPiece(52, 'Character', 'Character', 7),
    createPiece(53, 'Character', 'Character', 8),
    createPiece(54, 'Character', 'Character', 9),
    createPiece(55, 'Character', 'Character', 1),
    createPiece(56, 'Character', 'Character', 2),
    createPiece(57, 'Character', 'Character', 3),
    createPiece(58, 'Character', 'Character', 4),
    createPiece(59, 'Character', 'Character', 5),
    createPiece(60, 'Character', 'Character', 6),
    createPiece(61, 'Character', 'Character', 7),
    createPiece(62, 'Character', 'Character', 8),
    createPiece(63, 'Character', 'Character', 9),
    createPiece(64, 'Character', 'Character', 1),
    createPiece(65, 'Character', 'Character', 2),
    createPiece(66, 'Character', 'Character', 3),
    createPiece(67, 'Character', 'Character', 4),
    createPiece(68, 'Character', 'Character', 5),
    createPiece(69, 'Character', 'Character', 6),
    createPiece(70, 'Character', 'Character', 7),
    createPiece(71, 'Character', 'Character', 8),
    createPiece(72, 'Character', 'Character', 9),
    // ... repeat for three more sets of Character tiles (total 4 sets)

    // Dot tiles
    createPiece(73, 'Dot', 'Dot', 1),
    createPiece(74, 'Dot', 'Dot', 2),
    createPiece(75, 'Dot', 'Dot', 3),
    createPiece(76, 'Dot', 'Dot', 4),
    createPiece(77, 'Dot', 'Dot', 5),
    createPiece(78, 'Dot', 'Dot', 6),
    createPiece(79, 'Dot', 'Dot', 7),
    createPiece(80, 'Dot', 'Dot', 8),
    createPiece(81, 'Dot', 'Dot', 9),
    createPiece(82, 'Dot', 'Dot', 1),
    createPiece(83, 'Dot', 'Dot', 2),
    createPiece(84, 'Dot', 'Dot', 3),
    createPiece(85, 'Dot', 'Dot', 4),
    createPiece(86, 'Dot', 'Dot', 5),
    createPiece(87, 'Dot', 'Dot', 6),
    createPiece(88, 'Dot', 'Dot', 7),
    createPiece(89, 'Dot', 'Dot', 8),
    createPiece(90, 'Dot', 'Dot', 9),
    createPiece(91, 'Dot', 'Dot', 1),
    createPiece(92, 'Dot', 'Dot', 2),
    createPiece(93, 'Dot', 'Dot', 3),
    createPiece(94, 'Dot', 'Dot', 4),
    createPiece(95, 'Dot', 'Dot', 5),
    createPiece(96, 'Dot', 'Dot', 6),
    createPiece(97, 'Dot', 'Dot', 7),
    createPiece(98, 'Dot', 'Dot', 8),
    createPiece(99, 'Dot', 'Dot', 9),
    createPiece(100, 'Dot', 'Dot', 1),
    createPiece(101, 'Dot', 'Dot', 2),
    createPiece(102, 'Dot', 'Dot', 3),
    createPiece(103, 'Dot', 'Dot', 4),
    createPiece(104, 'Dot', 'Dot', 5),
    createPiece(105, 'Dot', 'Dot', 6),
    createPiece(106, 'Dot', 'Dot', 7),
    createPiece(107, 'Dot', 'Dot', 8),
    createPiece(108, 'Dot', 'Dot', 9),
    // ... repeat for three more sets of Dot tiles (total 4 sets)

    // Wind tiles
    createPiece(109, 'Wind', 'East', null),
    createPiece(110, 'Wind', 'South', null),
    createPiece(111, 'Wind', 'West', null),
    createPiece(112, 'Wind', 'North', null),
    createPiece(113, 'Wind', 'East', null),
    createPiece(114, 'Wind', 'South', null),
    createPiece(115, 'Wind', 'West', null),
    createPiece(116, 'Wind', 'North', null),
    createPiece(117, 'Wind', 'East', null),
    createPiece(118, 'Wind', 'South', null),
    createPiece(119, 'Wind', 'West', null),
    createPiece(120, 'Wind', 'North', null),
    createPiece(121, 'Wind', 'East', null),
    createPiece(122, 'Wind', 'South', null),
    createPiece(123, 'Wind', 'West', null),
    createPiece(124, 'Wind', 'North', null),
    // ... repeat for three more sets of Wind tiles (total 4 sets)

    // Dragon tiles
    createPiece(125, 'Dragon', 'Red', null),
    createPiece(126, 'Dragon', 'Green', null),
    createPiece(127, 'Dragon', 'White', null),
    createPiece(128, 'Dragon', 'Red', null),
    createPiece(129, 'Dragon', 'Green', null),
    createPiece(130, 'Dragon', 'White', null),
    createPiece(131, 'Dragon', 'Red', null),
    createPiece(132, 'Dragon', 'Green', null),
    createPiece(133, 'Dragon', 'White', null),
    createPiece(134, 'Dragon', 'Red', null),
    createPiece(135, 'Dragon', 'Green', null),
    createPiece(136, 'Dragon', 'White', null),
];